image: python:3.10

before_script:
  - apt-get update -y
  - apt-get install -y libpam0g-dev unzip openssh-server iputils-ping

  - useradd -m developer
  - echo -e "developer\ndeveloper" | passwd developer

  - pip install tox
    
  - export SOURCE_ROOT="$(pwd)"
  - export DEV_USER=developer
  - gemstone/installGemStone.sh 3.7.2
  - su -lc "$SOURCE_ROOT/gemstone/defineGemStoneEnvironment.sh 3.7.2" developer

test_parseltongue:
  script:
    - su -lc "echo $GEMSTONE" developer
    - su -lc "echo $SOURCE_ROOT -- $(pwd)" developer
    - su -lc "cd $SOURCE_ROOT; tox" developer
