image: python:3.5

before_script:
  - apt-get update -y
  - apt-get install -y libpam0g-dev unzip openssh-server

  - useradd -m developer
  - echo -e "developer\ndeveloper" | passwd developer

  - pip install tox
    
  - export SOURCE_ROOT="$(pwd)"
  - export DEV_USER=developer
  - gemstone/installGemStone.sh 3.6.1
  - gemstone/defineGemStoneEnvironment.sh 3.6.1

test_parseltongue:
  script:
    - su -lc "$SOURCE_ROOT/gemstone/defineGemStoneEnvironment.sh 3.6.1" developer
    - su -lc "echo $GEMSTONE" developer
    - su -lc "cd $SOURCE_ROOT; echo GEMSTONE1 -$GEMSTONE-; tox" developer
