image: python:3.5

before_script:
  - apt-get update -y
  - apt-get install -y libpam0g-dev unzip openssh-server

  - useradd -m vagrant
  - echo -e "vagrant\nvagrant" | passwd vagrant

  - pip install tox cython
  
  - gemstone/installGemStone.sh 3.4.1
  - gemstone/defineGemStoneEnvironment.sh 3.4.1
  - export SOURCE_ROOT="$(pwd)"

test_parseltongue:
  script:
    - whoami
    - ls -la /bin/sh
    - cat ~vagrant/.profile
    - su -lc "ps aux" vagrant
    - su -lc "ls -la /bin/sh" vagrant
    - su -lc "ls -la ~/.profile" vagrant
    - su -lc "cat ~/.profile" vagrant
    - su -lc "set" vagrant
    - su -lc "cd $SOURCE_ROOT; tox" vagrant