image: python:3.5

before_script:
  - apt-get update -y
  - apt-get install -y libpam0g-dev unzip openssh-server

  - useradd -m developer
  - echo -e "developer\ndeveloper" | passwd developer

  - gemstone/installGemStone.sh 3.6.1
  - gemstone/defineGemStoneEnvironment.sh 3.6.1
  - export SOURCE_ROOT="$(pwd)"
  - export DEV_USER=developer

test_parseltongue:
  script:
    - su -lc "cd $SOURCE_ROOT; tox" vagrant
